# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_message_target_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='target_group',
            new_name='select_group',
        ),
        migrations.AddField(
            model_name='message',
            name='select_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
